version: '3.9'

services:
  app1:
    build: ./app
    ports: 
      - 3000:3000
    environment:
      - HOSTNAME=app1
      - PORT=3000
  app2:
    build: ./app
    ports: 
      - 3001:3000
    environment:
      - HOSTNAME=app2
      - PORT=3001
  app3:
    build: ./app
    ports: 
      - 3002:3000
    environment:
      - HOSTNAME=app3
      - PORT=3002

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3

